### ISSUE TITLE
How to display the remote media stream using render method?

### ISSUE THREAD

**Issue by jawandarajbir** [rtc-io/rtc-media#12]
I noticed the way render method works for local media stream, where you can specify the target before getusermedia gets called. 
In case of remote stream scenario, we have already got the stream object ready, how to show it on  page using render method?

**Comment by DamonOehlman** [comment]
Hey mate - Yeah, this is a little vague in the documentation - I'll leave this issue open until it's fixed.

In the meantime though, here's how you do it:

``` js
  quickconnect('http://rtc.io/switchboard/', { room: 'conftest' })
    // broadcast our captured media to other participants in the room
    .addStream(stream)
    // when a peer is connected (and active) pass it to us for use
    .on('call:started', function(id, pc, data) {
      // render the remote streams
      pc.getRemoteStreams().forEach(function(stream) {
        var el = media(stream).render(document.body);

        // set the data-peer attribute of the element
        el.dataset.peer = id;
      });
    })
    // when a peer leaves, remove the media
    .on('call:ended', function(id) {
      // remove video elements associated with the remote peer
      qsa('video[data-peer="' + id + '"]').forEach(function(el) {
        el.parentNode.removeChild(el);
      });
    });
```

Example taken from an interactive guidebook that I've started work on for rtc.io stuff:

http://rtc.io/guidebook/RemoteStreams.md

Hope that helps :)
